language: node_js
node_js:
- '7'
before_install:
- openssl aes-256-cbc -K $encrypted_d5913473cb86_key -iv $encrypted_d5913473cb86_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod 600 id_rsa
- cp id_rsa ~/.ssh/id_rsa
before_script:
- npm install -g gulp
script:
- gulp
- bash deploy
