language: node_js
node_js:
- '7'
before_script:
- npm install -g gulp
script:
- gulp
- gulp install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
  
